title: "&7Vanish Settings"

enabled-lore:
  - '&7Enabled'
disabled-lore:
  - '&7Disabled'

names:
  enable-all: "&c&lENABLE ALL"
  silent-chest: "&d&lSilent Chest"
  physical-actions: "&e&lNO PHYSICAL ACTIONS"
  animations: "&b&lNO ANIMATIONS"
  pickups: "&a&lNO PICKUPS"
  disable-all: "&c&lRESET"
