name: LightVanish
version: '${project.version}'
main: ru.kainlight.lightvanish.Main
api-version: 1.16
author: kainlight
depend: [LuckPerms, ProtocolLib]
softdepend: [PlaceholderAPI]

commands:
  lightvanish:
    aliases:
      - lv
      - vanish
      - v

permissions:
  lightvanish.silent.chest:
    default: op
  lightvanish.silent.chest.editing:
    default: op
  lightvanish.silent.*:
    default: op
    children:
      lightvanish.silent.chest: true
      lightvanish.silent.chest.editing: true
  lightvanish.bypass.physical:
    default: op
  lightvanish.bypass.worlds:
    default: op
  lightvanish.bypass.pickup:
    default: op
  lightvanish.bypass.place:
    default: op
  lightvanish.bypass.*:
    default: op
    children:
      lightvanish.bypass.worlds: true
      lightvanish.bypass.pickup: true
      lightvanish.bypass.place: true
      lightvanish.bypass.physical: true
  lightvanish.use:
    default: op
  lightvanish.use.other:
    default: op
  lightvanish.use.*:
    default: op
  lightvanish.list:
    default: op
  lightvanish.show-all:
    default: op
  lightvanish.*:
    default: op
    children:
      lightvanish.list: true
      lightvanish.protected: true
      lightvanish.use.*: true
      lightvanish.silent.*: true
      lightvanish.bypass.*: true
      lightvanish.show-all: true

