name: LightVanish
version: '${project.version}'
main: ru.kainlight.lightvanish.Main
api-version: 1.16
author: kainlight
depend: [LuckPerms]
softdepend: [PlaceholderAPI]

commands:
  lightvanish:
    aliases:
      - lv
      - vanish
      - v

permissions:
  lightvanish.bypass.worlds:
    default: op
  lightvanish.bypass.place:
    default: op
  lightvanish.bypass.*:
    default: op
    children:
      lightvanish.bypass.worlds: true
      lightvanish.bypass.place: true
  lightvanish.settings:
    default: op
  lightvanish.use:
    default: op
  lightvanish.use.other:
    default: op
  lightvanish.use.*:
    default: op
  lightvanish.list:
    default: op
  lightvanish.show-all:
    default: op
  lightvanish.chest.editing:
    default: op
  lightvanish.*:
    default: op
    children:
      lightvanish.list: true
      lightvanish.protected: true
      lightvanish.use.*: true
      lightvanish.bypass.*: true
      lightvanish.chest.editing: true
      lightvanish.settings: true
      lightvanish.show-all: true

